### ISSUE TITLE
No open button

### ISSUE THREAD

**Issue by Deltafox79** [Enyby/APK-Info#7]
Hi, why is not the Open File button implemented to avoid launching the app every time to check every single apk?

**Comment by Enyby** [comment]
Read Readme.md:

> Using
> 
> You can open the APK file in APK-Info using one of the following methods:
> 
>     Start APK-Info, and then select the APK file in the dialog.
>     Drag the APK file to APK-Info.exe or its shortcut.
>     Drag the APK file into the running APK-Info window.
>     Open the APK file by double-clicking, after installing APK-Info, as a program for opening APK files (via explorer or attached .cmd file).
