### ISSUE TITLE
APK-Info.exe being flagged as unsafe by Symantec Antivirus

### ISSUE THREAD

**Issue by liorabel** [Enyby/APK-Info#8]
Starting with APK-Info 1.28 and onward (up to 1.30), Symantec Antivirus blocks and then deletes APK-Info.exe under the category [WS.Reputation.1](https://www.symantec.com/security-center/writeup/2010-051308-1854-99).
This is a general catch-all category for threats under Symantec and seems to be some sort of crowdsourced way of judging a file's "reputation".

I already submitted this into the [Symantec 'false positive' dispute form](https://submit.symantec.com/false_positive/), but perhaps there is a deeper root cause for this that could be looked at on the development side. As mentioned above, this only started happening for versions 1.28 and up.

**Comment by patrickdrd** [comment]
I confirm, same thing happens with avast antivirus, I had to add in exclusions in order for it to work,
I'm posting this link to xda thread

**Comment by sadonly** [comment]
same false positive with avg

**Comment by liorabel** [comment]
Symantec responded to my dispute with the following:

> In relation to submission 110880.
> 
> Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:
> 
>     File name: APK-Info.exe
>     MD5: DEE9640283B1A72E401BCD5399943FB1
>     SHA256: F2470CED71DC43B894EFE5232DCAA186050F19A6A0393ACB06D0C289040B7BFE
>     Note: Whitelisting may take up to 24 hours to take effect via Live Update

FYI, that was for my submission of APK-Info.exe 1.30. I do not know if this will also cover 1.28, 1.29, or any future versions.

**Comment by Enyby** [comment]
This is a common problem for any applications built on AutoIt. For my part, nothing can be done.

Send reports to anti-virus companies. This is the only thing you can do.

https://github.com/Enyby/APK-Info/issues/4#issuecomment-403237230
