### ISSUE TITLE
Shell Integration don't work here.

### ISSUE THREAD

**Issue by mikhoul** [Enyby/APK-Info#9]
I'm under windows 7 I even restarted the shell and I see nothing when I select an APK  with the right click menu.

![image](https://user-images.githubusercontent.com/5678673/48033117-098d5980-e128-11e8-82bc-3683b71238de.png)

![image](https://user-images.githubusercontent.com/5678673/48033048-c501be00-e127-11e8-9d8c-2d1d66da8ec3.png)

Regards :octocat:

**Comment by Enyby** [comment]
Make double click on .apk file.

**Comment by ibuprophen1** [comment]
@mikhoul, try right clicking on the " 	APK-Info-Shell-Integration.bat" file and select the option to Run as Administrator. 

Sometimes that does the trick... 


~Ibuprophen

**Comment by mikhoul** [comment]
@ibuprophen1   I've found the bug with the script: I use for default application Winrar/7zip to open APK so when I change it to "APK-Info"  it put APK-info in the context menu but NOT when I use 7zip as default application to open APK files.

Could you fix it so we could use whatever application we want to open APK and having "APK Info" in the contextual menu ? 

You just have to create the registry key like this in "HKEY_CLASSES_ROOT\*\shell " like this:

![image](https://user-images.githubusercontent.com/5678673/48089145-c1c30c80-e1d1-11e8-9c78-0fd6469cc72a.png)

![image](https://user-images.githubusercontent.com/5678673/48089187-d901fa00-e1d1-11e8-875d-a7f46b50ffa1.png)


Regards :octocat:

**Comment by ibuprophen1** [comment]
@mikhoul, it's there already... 

If you look at the following batch file... 

https://github.com/Enyby/APK-Info/blob/master/APK-Info-Shell-Integration.bat

... You'll notice this as reflected on the lines beginning with "REG ADD "HKCR". 

I'm not the developer for this but, I am curious as to why @Enyby didn't go with a registry (.reg) file when approaching this goal. Typically going with a .reg route is less likely to fail than going the .bat route. 

I can only suggest/recommend... 


~Ibuprophen

**Comment by mikhoul** [comment]
[**@ibuprophen1**](https://github.com/ibuprophen1) commented on [6 nov. 2018 à 15:45 UTC−5](https://github.com/Enyby/APK-Info/issues/9#issuecomment-436402256 "2018-11-06T20:45:33Z - Replied by Github Reply Comments"):
> [@mikhoul](https://github.com/mikhoul), it's there already...
> 
> ... You'll notice this as reflected on the lines beginning with "REG ADD "HKCR".
> 

> 
> ~Ibuprophen

This script  or .bat file only change "HKCR" key for the .APK extension files so if you have anything else than APK-Info.exe for default application for APK files it will not work.

Look closely at the picture in my post the right key to have it working with any default applications for APK files is  "HKEY_CLASSES_ROOT*\shell"   With the "*" in the path which mean it will always be visible in the contextual menu.  

The script approach is better IMO because people that are not familiar with the registry just run the bat file and it pickup variable and fulfill them automatically with no intervention from the user. :smile: 

The problem is just that the information are not registered in the  "HKEY_CLASSES_ROOT*\shell" but in the ""HKCR\.apk" key which only work if APK-Info.exe for default application for APK files. 

Regards :octocat:

**Comment by Enyby** [comment]
This is not my approach. This was done before me and not by me.
I generally think that in Windows 7 you can select "open with" and select APK-Info on the disk. and do not need any .reg or .bat files.
Frankly, I did not use it and do not know what it is doing there.

**Comment by ibuprophen1** [comment]
Thank you very much for the response @Enyby! 👍

Since removing it may wind up in a negative way with individuals who use it asking for it back... 

Maybe you can relocate the batch file within in a New Directory/Folder that's labeled something like "Deprecated-Shell-Integration-Batch-File". 

This way it's still there but, clearly labeled as such. 

I can create a few pull requests reflecting this but, someone with the Admin Rights of the Repo can actually do this much faster and easier. 

Just a suggestion/recommendation My Friend. 


~Ibuprophen

**Comment by ibuprophen1** [comment]
I just remembered that an individual can also, alternatively, go to the location... 

Open the Run prompt (via Start Menu or by using the key combo of Pressing & hold the Windows Key and then press the R key and release the keys) and type the following... 

%APPDATA%\Microsoft\Windows\SendTo\

Then place a "Shortcut" of the Apk Info exe file within it... Then exit. 

Now the Apk Info will be seen when you Right Click and scroll down to the Send To entry of the context menu and it'll be there. 

Another suggestion... 


~Ibuprophen

**Comment by Enyby** [comment]
> When I've created files for performing tasks specific to the registry, I've preferred to use registry ".reg" files for merging.

You can not use .reg file because path can not different. So you need .bat file.

> Could you fix it so we could use whatever application we want to open APK and having "APK Info" in the contextual menu ?

It is not "fix". It is complete different things.

**Comment by oeloo** [comment]
Hi, the .bat does not work in windows 11 due to this :
![image](https://user-images.githubusercontent.com/98819304/228175762-e67cf0d6-8f56-473b-a52f-1cefdfbae956.png)

I have modified it so that it works:
```
@ECHO OFF

ECHO APK-Info shell integration...
ECHO.

for %%H in (HKCU) do (
	REG ADD "%%H\SOFTWARE\Classes\.apk" /ve /t REG_SZ /d "APK-Info" /f >nul 2>nul
	REG ADD "%%H\SOFTWARE\Classes\APK-Info\DefaultIcon" /ve /t REG_SZ /d "%cd%\APK-Info.exe" /f >nul 2>nul
	REG ADD "%%H\SOFTWARE\Classes\APK-Info\shell\open" /ve /t REG_SZ /d "APK-Info" /f >nul 2>nul
	REG ADD "%%H\SOFTWARE\Classes\APK-Info\shell\open\command" /ve /t REG_SZ /d "%cd%\APK-Info.exe %%1" /f >nul 2>nul
	
	REG ADD "%%H\SOFTWARE\Classes\SystemFileAssociations\.apk\Shell\APK-Info\Command" /ve /t REG_SZ /d "%cd%\APK-Info.exe %%1" /f >nul 2>nul
)

ECHO APK-Info shell integration completed!
ECHO.
ECHO.
ECHO     **** Press any key to exit ****
pause > NUL
```
